### ISSUE TITLE
About component upheaval

### ISSUE THREAD

**Issue by PradyumnaShome** [ReflectionsProjections/ReflectionsProjections.github.io#82]
Use R|P 2016 website as reference. Link: [R|P 2016](https://www-s.acm.illinois.edu/conference/2016/)

Tasks:

- [ ] Move countdown down from `Start` component
- [x] Migrate "What is R|P?" from FAQ to About
- [ ] Migrate "Who can attend?" from FAQ to About
- [x] Add event highlights / blurbs for each event as follows:
  - [x] Event Highlights
       - [x] Primary Events
            - [x] Career Fair
            - [x] Startup Fair
            - [x] Speakers
            - [x] MechMania - Don’t wait for Issue #42. Use “more info coming soon” in place
            - [x] PuzzleBang - Don’t wait for Issue #42. Use “more info coming soon” in place
            - [x] ACM Symposium - Don’t wait for Issue #42. Use “more info coming soon” in place
      - [x] Extra Events
          - [x] Speaker Socials
          - [x] Experiences
          - [x] Social Media Challenge

Feel free to clone the HTML from the old website and create components at the appropriate granularity as you see fit.

- [x] Remove three flip cards from where they are used (keep the declaration for now)

**Comment by PradyumnaShome** [comment]
@vidushirai @modnikhil  More stuff still remaining. Keep checking off boxes as stuff is merged in.
